name: Tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  run-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies (Linux)
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            gcc make \
            yq diffutils

      - name: Build project and run test suite
        run: make test

      - name: Upload test outputs
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-outputs-${{ matrix.os }}
          path: tests/outputs/
          if-no-files-found: ignore
